# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('categoryid', models.CharField(max_length=200)),
                ('brandname', models.CharField(max_length=200)),
                ('img1', models.CharField(max_length=200)),
                ('childcid1', models.CharField(max_length=200)),
                ('productid1', models.CharField(max_length=200)),
                ('longname1', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('marketprice1', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
                ('childcid2', models.CharField(max_length=200)),
                ('productid2', models.CharField(max_length=200)),
                ('longname2', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=20)),
                ('marketprice2', models.CharField(max_length=200)),
                ('img3', models.CharField(max_length=200)),
                ('childcid3', models.CharField(max_length=200)),
                ('productid3', models.CharField(max_length=200)),
                ('longname3', models.CharField(max_length=200)),
                ('price3', models.CharField(max_length=20)),
                ('marketprice3', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_mainshow',
            },
        ),
        migrations.CreateModel(
            name='MustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_nav',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_wheel',
            },
        ),
    ]
